---
- hosts: all
  become: yes
  tasks:

  - name: Install development tools
    yum: name={{ item }} state=present update_cache=yes
    with_items:
      - "@development-tools"
      - git
      - curl
      - htop
